//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.ClientResources", typeof(ClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountSettingsName {
            get {
                return ResourceManager.GetString("AccountSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string AudioSettingsName {
            get {
                return ResourceManager.GetString("AudioSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A basic tutorial that covers game basics.
        /// </summary>
        internal static string BasicTutorialDescription {
            get {
                return ResourceManager.GetString("BasicTutorialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Tutorial.
        /// </summary>
        internal static string BasicTutorialName {
            get {
                return ResourceManager.GetString("BasicTutorialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string ControlSettingsName {
            get {
                return ResourceManager.GetString("ControlSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2019 Jeffery Myers.
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Codebase
        ///Copyright 2019 Jeffery Myers
        ///
        ///Libraries
        ///UrhoSharp (c) Microsoft Corporation. All rights reserved.
        ///
        ///Third Party Asset Copyright Holders:
        ///BZFlag Assets, Copyright (c) 1993 - 2018 Tim Riker, Mozilla Public License version 2.0
        ///Exo2 Font, Copyright (c) 2013, Natanael Gama (www.ndiscovered.com . info(at)ndiscovered.com) Open Font License
        ///https://freesound.org/s/425368/ Copyright 2018 Soundholder CCBySA 3.0
        ///Music from https://filmmusic.io: &quot;Take a Chance&quot; by Kevin MacLeod (https://incompete [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreditText {
            get {
                return ResourceManager.GetString("CreditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used by developers to debug client code. 
        ///Allows the client to run without a server connection..
        /// </summary>
        internal static string DebugTutorialDescription {
            get {
                return ResourceManager.GetString("DebugTutorialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Tutorial.
        /// </summary>
        internal static string DebugTutorialName {
            get {
                return ResourceManager.GetString("DebugTutorialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game....
        /// </summary>
        internal static string JoinGame {
            get {
                return ResourceManager.GetString("JoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string LogSourceName {
            get {
                return ResourceManager.GetString("LogSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string NetworkSourceName {
            get {
                return ResourceManager.GetString("NetworkSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset folder was not found at $F.
        /// </summary>
        internal static string NoAssetPathError {
            get {
                return ResourceManager.GetString("NoAssetPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assets found.
        /// </summary>
        internal static string NoAssetPathErrorTitle {
            get {
                return ResourceManager.GetString("NoAssetPathErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        internal static string RenderSettingsName {
            get {
                return ResourceManager.GetString("RenderSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawned at .
        /// </summary>
        internal static string SpawnHudMesage {
            get {
                return ResourceManager.GetString("SpawnHudMesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn when ready.
        /// </summary>
        internal static string SpawnMessage {
            get {
                return ResourceManager.GetString("SpawnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SystemSourceName {
            get {
                return ResourceManager.GetString("SystemSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials....
        /// </summary>
        internal static string Tutorials {
            get {
                return ResourceManager.GetString("Tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutor.
        /// </summary>
        internal static string TutorialSourceName {
            get {
                return ResourceManager.GetString("TutorialSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPx0F.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
